name: "Dotnet project workflow"
on: 
  -
    push
jobs:
  build-step:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Getting Project From Repository"
        uses: actions/checkout@v2
      - 
        name: "Project Roots"
        run: pwd
      - 
        name: "List Of Folders"
        run: ls -la
      - 
        name: "Project building"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
        run: dotnet build .\DreamerMan.sln
        


