name: "Dotnet project workflow"
on: 
  -
    push
jobs:
  build-step:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Getting Project From Repository"
        uses: actions/checkout@v2
      - 
        name: "Project Roots"
        run: pwd
      - 
        name: "List Of Folders"
        run: ls -la
      - 
        name: "Setup Dotnet"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      -
        name: "Project Building"
        run: dotnet build
      -
        name: "Project Restoring"
        run: dotnet restore
      -
        name: "Project Testing"
        run: dotnet test -v q



